kumuluzee:
  name: placila-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  cors-filter:
    annotations:
      placila:
        allow-origin: "*"
        allow-subdomains: true
  datasources:
    - jndi-name: jdbc/PlacilaDS
      connection-url: jdbc:postgresql://192.168.99.100:5434/racuni
      username: dbuser
      password: postgres
  config:
    consul:
      agent: http://192.168.99.100:8500
  discovery:
    cluster: 1
    consul:
      agent: http://192.168.99.100:8500
    ttl: 20
    ping-interval: 15
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/PlacilaDS
    metrics:
      web-instrumentation:
        - name: placila-endpoint
          url-pattern: /v1/placila/*

rest-properties:
  maintenance-mode: false
  broken: false
  price-per-hour: 3
